import Header from '@/components/UI/Header'
import { ConfigProvider, Flex } from 'antd'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Image from 'next/image'
import logo from '../../public/logo.png'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ConfigProvider theme={{
          token: {
            colorPrimary: '28c0e9',
          },
          components: {
            Button: {
              controlHeight: 56,
              borderRadius: 20,
            },
          }
        }}>
          <Header />
          {children}
        </ConfigProvider>
      </body>
    </html>
  )
}
